# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'draft' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for draft
  pod 'RxKakaoSDKAuth', '~> 2.0.0-beta.5'
  pod 'RxKakaoSDKCommon', '~> 2.0.0-beta.5'
#  pod 'Alamofire', '~> 5.2'
  pod 'Alamofire'
  pod 'RxSwift' #, '~> 5'
  pod 'RxCocoa' #, '~> 5'
  pod 'DynamicCodable' #, '1.0'
  
  pod 'FBSDKLoginKit'
  
  target 'draftTests' do
    # inherit! :search_paths
    # Pods for testing
  end

  target 'draftUITests' do
    # Pods for testing
  end

  
end
