# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'draft' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for draft
  pod 'RxKakaoSDK', '~> 2.0.0-beta.3'
  pod 'Alamofire', '~> 5.2'
  pod 'RxAlamofire'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'DynamicCodable', '1.0'
  
  target 'draftTests' do
    # inherit! :search_paths
    # Pods for testing
  end

  target 'draftUITests' do
    # Pods for testing
  end

  
end
