# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Draft' do
  # Comment the next line if you don't want to use dynamic frameworks
	# use_frameworks!

  pod 'KakaoSDKAuth'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'
  pod 'Alamofire'
  pod 'DynamicCodable' #, '1.0'
  pod 'GoogleSignIn'
  pod 'KeychainAccess', '~> 4.2'
  pod 'RxSwift'

	target 'DraftTests' do
    inherit! :complete
  end

	target 'DraftUITests' do
 		inherit! :complete
 	end
end
