name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild
      env:
          DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    - name: Run tests
      run: xcodebuild # Test script로 수정해야
      env:
          DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
