name: Swift

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GnuPG
      run: brew install GnuPG
    - name: Decrypt secrets
      run: .provisioning/provisioning.sh
      env:
        PROVISIONING_CRYPT_PASSWORD: ${{ secrets.PROVISIONING_CRYPT_PASSWORD }}
        CERTIFICATE_CRYPT_PASSWORD: ${{ secrets.CERTIFICATE_CRYPT_PASSWORD }}
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app && xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -workspace draft/draft.xcworkspace -configuration Release -scheme Draft -derivedDataPath DerivedData -archivePath DerivedData/Archive/Draft -allowProvisioningUpdates archive
    - name: Export archive
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/Draft.xcarchive -exportOptionsPlist .provisioning/App-Store.plist -exportPath DerivedData/ipa -allowProvisioningUpdates
    - name: Show file hierarchy
      run: ls -R
    - name: Deploy to Apple
      run: xcrun altool --upload-app --type ios --file DerivedData/ipa/Draft.ipa \
          --username "${{ secrets.APPSTORE_CONNECT_USERNAME }}" --password "${{ secrets.APPSTORE_CONNECT_PASSWORD }}" --verbose
      
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Add secret_login.json
#      run: |
#          cat << EOF > ./draft/draft/Controllers/secret_login.json
#          ${{ secrets.secret_login }}
#          EOF
#    - name: Build Workspace (Xcode 11.5 & iOS 13.5 & iPhone 11)
#      run: xcodebuild clean build -workspace draft/draft.xcworkspace -destination "platform=iOS Simulator,name=iPhone 11,OS=13.5" -scheme Draft IPHONEOS_DEPLOYMENT_TARGET=13.5
#
#      env:
#          DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
