name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add secret_login.json
      run: |
          cat << EOF > ./draft/draft/Controllers/secret_login.json
          ${{ secrets.secret_login }}
          EOF
    - name: Build Workspace (Xcode 11.5 & iOS 13.5 & iPhone 11)
      run: xcodebuild clean build -workspace draft/draft.xcworkspace -destination "platform=iOS Simulator,name=iPhone 11,OS=13.5" -scheme Draft IPHONEOS_DEPLOYMENT_TARGET=13.5

      env:
          DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
#     - name: Run tests
#       run: xcodebuild clean test -project draft/draft.xcodeproj -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3" -scheme draft IPHONEOS_DEPLOYMENT_TARGET=13.2

#       env:
#           DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
